THREAD_COUNT=12
[ ! -f "sa_0_20.png" ] && ./build/pbrt sa_0_20.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_22.png" ] && ./build/pbrt sa_0_22.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_24.png" ] && ./build/pbrt sa_0_24.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_26.png" ] && ./build/pbrt sa_0_26.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_28.png" ] && ./build/pbrt sa_0_28.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_30.png" ] && ./build/pbrt sa_0_30.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_32.png" ] && ./build/pbrt sa_0_32.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_34.png" ] && ./build/pbrt sa_0_34.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_36.png" ] && ./build/pbrt sa_0_36.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_38.png" ] && ./build/pbrt sa_0_38.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_40.png" ] && ./build/pbrt sa_0_40.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_42.png" ] && ./build/pbrt sa_0_42.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_44.png" ] && ./build/pbrt sa_0_44.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_46.png" ] && ./build/pbrt sa_0_46.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_48.png" ] && ./build/pbrt sa_0_48.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_50.png" ] && ./build/pbrt sa_0_50.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_52.png" ] && ./build/pbrt sa_0_52.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_54.png" ] && ./build/pbrt sa_0_54.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_56.png" ] && ./build/pbrt sa_0_56.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_58.png" ] && ./build/pbrt sa_0_58.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_60.png" ] && ./build/pbrt sa_0_60.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_62.png" ] && ./build/pbrt sa_0_62.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_64.png" ] && ./build/pbrt sa_0_64.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_66.png" ] && ./build/pbrt sa_0_66.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_68.png" ] && ./build/pbrt sa_0_68.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_70.png" ] && ./build/pbrt sa_0_70.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_72.png" ] && ./build/pbrt sa_0_72.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_74.png" ] && ./build/pbrt sa_0_74.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_76.png" ] && ./build/pbrt sa_0_76.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_78.png" ] && ./build/pbrt sa_0_78.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_80.png" ] && ./build/pbrt sa_0_80.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_82.png" ] && ./build/pbrt sa_0_82.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_84.png" ] && ./build/pbrt sa_0_84.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_86.png" ] && ./build/pbrt sa_0_86.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_88.png" ] && ./build/pbrt sa_0_88.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_90.png" ] && ./build/pbrt sa_0_90.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_92.png" ] && ./build/pbrt sa_0_92.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_94.png" ] && ./build/pbrt sa_0_94.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_96.png" ] && ./build/pbrt sa_0_96.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_0_98.png" ] && ./build/pbrt sa_0_98.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_00.png" ] && ./build/pbrt sa_1_00.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_02.png" ] && ./build/pbrt sa_1_02.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_04.png" ] && ./build/pbrt sa_1_04.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_06.png" ] && ./build/pbrt sa_1_06.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_08.png" ] && ./build/pbrt sa_1_08.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_10.png" ] && ./build/pbrt sa_1_10.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_12.png" ] && ./build/pbrt sa_1_12.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_14.png" ] && ./build/pbrt sa_1_14.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_16.png" ] && ./build/pbrt sa_1_16.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_18.png" ] && ./build/pbrt sa_1_18.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_20.png" ] && ./build/pbrt sa_1_20.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_22.png" ] && ./build/pbrt sa_1_22.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_24.png" ] && ./build/pbrt sa_1_24.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_26.png" ] && ./build/pbrt sa_1_26.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_28.png" ] && ./build/pbrt sa_1_28.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_30.png" ] && ./build/pbrt sa_1_30.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_32.png" ] && ./build/pbrt sa_1_32.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_34.png" ] && ./build/pbrt sa_1_34.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_36.png" ] && ./build/pbrt sa_1_36.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_38.png" ] && ./build/pbrt sa_1_38.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_40.png" ] && ./build/pbrt sa_1_40.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_42.png" ] && ./build/pbrt sa_1_42.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_44.png" ] && ./build/pbrt sa_1_44.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_46.png" ] && ./build/pbrt sa_1_46.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_48.png" ] && ./build/pbrt sa_1_48.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_50.png" ] && ./build/pbrt sa_1_50.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_52.png" ] && ./build/pbrt sa_1_52.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_54.png" ] && ./build/pbrt sa_1_54.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_56.png" ] && ./build/pbrt sa_1_56.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_58.png" ] && ./build/pbrt sa_1_58.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_60.png" ] && ./build/pbrt sa_1_60.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_62.png" ] && ./build/pbrt sa_1_62.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_64.png" ] && ./build/pbrt sa_1_64.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_66.png" ] && ./build/pbrt sa_1_66.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_68.png" ] && ./build/pbrt sa_1_68.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_70.png" ] && ./build/pbrt sa_1_70.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_72.png" ] && ./build/pbrt sa_1_72.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_74.png" ] && ./build/pbrt sa_1_74.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_76.png" ] && ./build/pbrt sa_1_76.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_78.png" ] && ./build/pbrt sa_1_78.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_80.png" ] && ./build/pbrt sa_1_80.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_82.png" ] && ./build/pbrt sa_1_82.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_84.png" ] && ./build/pbrt sa_1_84.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_86.png" ] && ./build/pbrt sa_1_86.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_88.png" ] && ./build/pbrt sa_1_88.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_90.png" ] && ./build/pbrt sa_1_90.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_92.png" ] && ./build/pbrt sa_1_92.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_94.png" ] && ./build/pbrt sa_1_94.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_96.png" ] && ./build/pbrt sa_1_96.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_1_98.png" ] && ./build/pbrt sa_1_98.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_00.png" ] && ./build/pbrt sa_2_00.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_02.png" ] && ./build/pbrt sa_2_02.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_04.png" ] && ./build/pbrt sa_2_04.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_06.png" ] && ./build/pbrt sa_2_06.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_08.png" ] && ./build/pbrt sa_2_08.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_10.png" ] && ./build/pbrt sa_2_10.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_12.png" ] && ./build/pbrt sa_2_12.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_14.png" ] && ./build/pbrt sa_2_14.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_16.png" ] && ./build/pbrt sa_2_16.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_18.png" ] && ./build/pbrt sa_2_18.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_20.png" ] && ./build/pbrt sa_2_20.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_22.png" ] && ./build/pbrt sa_2_22.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_24.png" ] && ./build/pbrt sa_2_24.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_26.png" ] && ./build/pbrt sa_2_26.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_28.png" ] && ./build/pbrt sa_2_28.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_30.png" ] && ./build/pbrt sa_2_30.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_32.png" ] && ./build/pbrt sa_2_32.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_34.png" ] && ./build/pbrt sa_2_34.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_36.png" ] && ./build/pbrt sa_2_36.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_38.png" ] && ./build/pbrt sa_2_38.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_40.png" ] && ./build/pbrt sa_2_40.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_42.png" ] && ./build/pbrt sa_2_42.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_44.png" ] && ./build/pbrt sa_2_44.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_46.png" ] && ./build/pbrt sa_2_46.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_48.png" ] && ./build/pbrt sa_2_48.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_50.png" ] && ./build/pbrt sa_2_50.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_52.png" ] && ./build/pbrt sa_2_52.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_54.png" ] && ./build/pbrt sa_2_54.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_56.png" ] && ./build/pbrt sa_2_56.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_58.png" ] && ./build/pbrt sa_2_58.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_60.png" ] && ./build/pbrt sa_2_60.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_62.png" ] && ./build/pbrt sa_2_62.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_64.png" ] && ./build/pbrt sa_2_64.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_66.png" ] && ./build/pbrt sa_2_66.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_68.png" ] && ./build/pbrt sa_2_68.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_70.png" ] && ./build/pbrt sa_2_70.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_72.png" ] && ./build/pbrt sa_2_72.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_74.png" ] && ./build/pbrt sa_2_74.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_76.png" ] && ./build/pbrt sa_2_76.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_78.png" ] && ./build/pbrt sa_2_78.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_80.png" ] && ./build/pbrt sa_2_80.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_82.png" ] && ./build/pbrt sa_2_82.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_84.png" ] && ./build/pbrt sa_2_84.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_86.png" ] && ./build/pbrt sa_2_86.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_88.png" ] && ./build/pbrt sa_2_88.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_90.png" ] && ./build/pbrt sa_2_90.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_92.png" ] && ./build/pbrt sa_2_92.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_94.png" ] && ./build/pbrt sa_2_94.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_96.png" ] && ./build/pbrt sa_2_96.pbrt --nthreads $THREAD_COUNT
[ ! -f "sa_2_98.png" ] && ./build/pbrt sa_2_98.pbrt --nthreads $THREAD_COUNT
