THREAD_COUNT=12
[ ! -f "focus0.20.png" ] && ./build/pbrt focus_0.20.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.21.png" ] && ./build/pbrt focus_0.21.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.22.png" ] && ./build/pbrt focus_0.22.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.23.png" ] && ./build/pbrt focus_0.23.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.24.png" ] && ./build/pbrt focus_0.24.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.25.png" ] && ./build/pbrt focus_0.25.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.26.png" ] && ./build/pbrt focus_0.26.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.27.png" ] && ./build/pbrt focus_0.27.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.28.png" ] && ./build/pbrt focus_0.28.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.29.png" ] && ./build/pbrt focus_0.29.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.30.png" ] && ./build/pbrt focus_0.30.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.31.png" ] && ./build/pbrt focus_0.31.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.32.png" ] && ./build/pbrt focus_0.32.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.33.png" ] && ./build/pbrt focus_0.33.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.34.png" ] && ./build/pbrt focus_0.34.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.35.png" ] && ./build/pbrt focus_0.35.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.36.png" ] && ./build/pbrt focus_0.36.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.37.png" ] && ./build/pbrt focus_0.37.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.38.png" ] && ./build/pbrt focus_0.38.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.39.png" ] && ./build/pbrt focus_0.39.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.40.png" ] && ./build/pbrt focus_0.40.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.41.png" ] && ./build/pbrt focus_0.41.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.42.png" ] && ./build/pbrt focus_0.42.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.43.png" ] && ./build/pbrt focus_0.43.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.44.png" ] && ./build/pbrt focus_0.44.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.45.png" ] && ./build/pbrt focus_0.45.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.46.png" ] && ./build/pbrt focus_0.46.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.47.png" ] && ./build/pbrt focus_0.47.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.48.png" ] && ./build/pbrt focus_0.48.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.49.png" ] && ./build/pbrt focus_0.49.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.50.png" ] && ./build/pbrt focus_0.50.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.51.png" ] && ./build/pbrt focus_0.51.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.52.png" ] && ./build/pbrt focus_0.52.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.53.png" ] && ./build/pbrt focus_0.53.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.54.png" ] && ./build/pbrt focus_0.54.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.55.png" ] && ./build/pbrt focus_0.55.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.56.png" ] && ./build/pbrt focus_0.56.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.57.png" ] && ./build/pbrt focus_0.57.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.58.png" ] && ./build/pbrt focus_0.58.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.59.png" ] && ./build/pbrt focus_0.59.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.60.png" ] && ./build/pbrt focus_0.60.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.61.png" ] && ./build/pbrt focus_0.61.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.62.png" ] && ./build/pbrt focus_0.62.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.63.png" ] && ./build/pbrt focus_0.63.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.64.png" ] && ./build/pbrt focus_0.64.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.65.png" ] && ./build/pbrt focus_0.65.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.66.png" ] && ./build/pbrt focus_0.66.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.67.png" ] && ./build/pbrt focus_0.67.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.68.png" ] && ./build/pbrt focus_0.68.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.69.png" ] && ./build/pbrt focus_0.69.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.70.png" ] && ./build/pbrt focus_0.70.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.71.png" ] && ./build/pbrt focus_0.71.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.72.png" ] && ./build/pbrt focus_0.72.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.73.png" ] && ./build/pbrt focus_0.73.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.74.png" ] && ./build/pbrt focus_0.74.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.75.png" ] && ./build/pbrt focus_0.75.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.76.png" ] && ./build/pbrt focus_0.76.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.77.png" ] && ./build/pbrt focus_0.77.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.78.png" ] && ./build/pbrt focus_0.78.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.79.png" ] && ./build/pbrt focus_0.79.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.80.png" ] && ./build/pbrt focus_0.80.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.81.png" ] && ./build/pbrt focus_0.81.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.82.png" ] && ./build/pbrt focus_0.82.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.83.png" ] && ./build/pbrt focus_0.83.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.84.png" ] && ./build/pbrt focus_0.84.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.85.png" ] && ./build/pbrt focus_0.85.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.86.png" ] && ./build/pbrt focus_0.86.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.87.png" ] && ./build/pbrt focus_0.87.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.88.png" ] && ./build/pbrt focus_0.88.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.89.png" ] && ./build/pbrt focus_0.89.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.90.png" ] && ./build/pbrt focus_0.90.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.91.png" ] && ./build/pbrt focus_0.91.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.92.png" ] && ./build/pbrt focus_0.92.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.93.png" ] && ./build/pbrt focus_0.93.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.94.png" ] && ./build/pbrt focus_0.94.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.95.png" ] && ./build/pbrt focus_0.95.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.96.png" ] && ./build/pbrt focus_0.96.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.97.png" ] && ./build/pbrt focus_0.97.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.98.png" ] && ./build/pbrt focus_0.98.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus0.99.png" ] && ./build/pbrt focus_0.99.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.00.png" ] && ./build/pbrt focus_1.00.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.01.png" ] && ./build/pbrt focus_1.01.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.02.png" ] && ./build/pbrt focus_1.02.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.03.png" ] && ./build/pbrt focus_1.03.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.04.png" ] && ./build/pbrt focus_1.04.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.05.png" ] && ./build/pbrt focus_1.05.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.06.png" ] && ./build/pbrt focus_1.06.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.07.png" ] && ./build/pbrt focus_1.07.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.08.png" ] && ./build/pbrt focus_1.08.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.09.png" ] && ./build/pbrt focus_1.09.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.10.png" ] && ./build/pbrt focus_1.10.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.11.png" ] && ./build/pbrt focus_1.11.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.12.png" ] && ./build/pbrt focus_1.12.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.13.png" ] && ./build/pbrt focus_1.13.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.14.png" ] && ./build/pbrt focus_1.14.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.15.png" ] && ./build/pbrt focus_1.15.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.16.png" ] && ./build/pbrt focus_1.16.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.17.png" ] && ./build/pbrt focus_1.17.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.18.png" ] && ./build/pbrt focus_1.18.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.19.png" ] && ./build/pbrt focus_1.19.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.20.png" ] && ./build/pbrt focus_1.20.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.21.png" ] && ./build/pbrt focus_1.21.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.22.png" ] && ./build/pbrt focus_1.22.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.23.png" ] && ./build/pbrt focus_1.23.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.24.png" ] && ./build/pbrt focus_1.24.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.25.png" ] && ./build/pbrt focus_1.25.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.26.png" ] && ./build/pbrt focus_1.26.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.27.png" ] && ./build/pbrt focus_1.27.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.28.png" ] && ./build/pbrt focus_1.28.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.29.png" ] && ./build/pbrt focus_1.29.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.30.png" ] && ./build/pbrt focus_1.30.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.31.png" ] && ./build/pbrt focus_1.31.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.32.png" ] && ./build/pbrt focus_1.32.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.33.png" ] && ./build/pbrt focus_1.33.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.34.png" ] && ./build/pbrt focus_1.34.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.35.png" ] && ./build/pbrt focus_1.35.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.36.png" ] && ./build/pbrt focus_1.36.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.37.png" ] && ./build/pbrt focus_1.37.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.38.png" ] && ./build/pbrt focus_1.38.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.39.png" ] && ./build/pbrt focus_1.39.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.40.png" ] && ./build/pbrt focus_1.40.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.41.png" ] && ./build/pbrt focus_1.41.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.42.png" ] && ./build/pbrt focus_1.42.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.43.png" ] && ./build/pbrt focus_1.43.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.44.png" ] && ./build/pbrt focus_1.44.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.45.png" ] && ./build/pbrt focus_1.45.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.46.png" ] && ./build/pbrt focus_1.46.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.47.png" ] && ./build/pbrt focus_1.47.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.48.png" ] && ./build/pbrt focus_1.48.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.49.png" ] && ./build/pbrt focus_1.49.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.50.png" ] && ./build/pbrt focus_1.50.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.51.png" ] && ./build/pbrt focus_1.51.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.52.png" ] && ./build/pbrt focus_1.52.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.53.png" ] && ./build/pbrt focus_1.53.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.54.png" ] && ./build/pbrt focus_1.54.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.55.png" ] && ./build/pbrt focus_1.55.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.56.png" ] && ./build/pbrt focus_1.56.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.57.png" ] && ./build/pbrt focus_1.57.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.58.png" ] && ./build/pbrt focus_1.58.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.59.png" ] && ./build/pbrt focus_1.59.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.60.png" ] && ./build/pbrt focus_1.60.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.61.png" ] && ./build/pbrt focus_1.61.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.62.png" ] && ./build/pbrt focus_1.62.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.63.png" ] && ./build/pbrt focus_1.63.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.64.png" ] && ./build/pbrt focus_1.64.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.65.png" ] && ./build/pbrt focus_1.65.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.66.png" ] && ./build/pbrt focus_1.66.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.67.png" ] && ./build/pbrt focus_1.67.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.68.png" ] && ./build/pbrt focus_1.68.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.69.png" ] && ./build/pbrt focus_1.69.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.70.png" ] && ./build/pbrt focus_1.70.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.71.png" ] && ./build/pbrt focus_1.71.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.72.png" ] && ./build/pbrt focus_1.72.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.73.png" ] && ./build/pbrt focus_1.73.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.74.png" ] && ./build/pbrt focus_1.74.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.75.png" ] && ./build/pbrt focus_1.75.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.76.png" ] && ./build/pbrt focus_1.76.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.77.png" ] && ./build/pbrt focus_1.77.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.78.png" ] && ./build/pbrt focus_1.78.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.79.png" ] && ./build/pbrt focus_1.79.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.80.png" ] && ./build/pbrt focus_1.80.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.81.png" ] && ./build/pbrt focus_1.81.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.82.png" ] && ./build/pbrt focus_1.82.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.83.png" ] && ./build/pbrt focus_1.83.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.84.png" ] && ./build/pbrt focus_1.84.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.85.png" ] && ./build/pbrt focus_1.85.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.86.png" ] && ./build/pbrt focus_1.86.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.87.png" ] && ./build/pbrt focus_1.87.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.88.png" ] && ./build/pbrt focus_1.88.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.89.png" ] && ./build/pbrt focus_1.89.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.90.png" ] && ./build/pbrt focus_1.90.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.91.png" ] && ./build/pbrt focus_1.91.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.92.png" ] && ./build/pbrt focus_1.92.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.93.png" ] && ./build/pbrt focus_1.93.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.94.png" ] && ./build/pbrt focus_1.94.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.95.png" ] && ./build/pbrt focus_1.95.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.96.png" ] && ./build/pbrt focus_1.96.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.97.png" ] && ./build/pbrt focus_1.97.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.98.png" ] && ./build/pbrt focus_1.98.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus1.99.png" ] && ./build/pbrt focus_1.99.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.00.png" ] && ./build/pbrt focus_2.00.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.01.png" ] && ./build/pbrt focus_2.01.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.02.png" ] && ./build/pbrt focus_2.02.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.03.png" ] && ./build/pbrt focus_2.03.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.04.png" ] && ./build/pbrt focus_2.04.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.05.png" ] && ./build/pbrt focus_2.05.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.06.png" ] && ./build/pbrt focus_2.06.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.07.png" ] && ./build/pbrt focus_2.07.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.08.png" ] && ./build/pbrt focus_2.08.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.09.png" ] && ./build/pbrt focus_2.09.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.10.png" ] && ./build/pbrt focus_2.10.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.11.png" ] && ./build/pbrt focus_2.11.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.12.png" ] && ./build/pbrt focus_2.12.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.13.png" ] && ./build/pbrt focus_2.13.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.14.png" ] && ./build/pbrt focus_2.14.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.15.png" ] && ./build/pbrt focus_2.15.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.16.png" ] && ./build/pbrt focus_2.16.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.17.png" ] && ./build/pbrt focus_2.17.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.18.png" ] && ./build/pbrt focus_2.18.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.19.png" ] && ./build/pbrt focus_2.19.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.20.png" ] && ./build/pbrt focus_2.20.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.21.png" ] && ./build/pbrt focus_2.21.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.22.png" ] && ./build/pbrt focus_2.22.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.23.png" ] && ./build/pbrt focus_2.23.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.24.png" ] && ./build/pbrt focus_2.24.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.25.png" ] && ./build/pbrt focus_2.25.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.26.png" ] && ./build/pbrt focus_2.26.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.27.png" ] && ./build/pbrt focus_2.27.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.28.png" ] && ./build/pbrt focus_2.28.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.29.png" ] && ./build/pbrt focus_2.29.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.30.png" ] && ./build/pbrt focus_2.30.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.31.png" ] && ./build/pbrt focus_2.31.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.32.png" ] && ./build/pbrt focus_2.32.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.33.png" ] && ./build/pbrt focus_2.33.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.34.png" ] && ./build/pbrt focus_2.34.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.35.png" ] && ./build/pbrt focus_2.35.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.36.png" ] && ./build/pbrt focus_2.36.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.37.png" ] && ./build/pbrt focus_2.37.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.38.png" ] && ./build/pbrt focus_2.38.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.39.png" ] && ./build/pbrt focus_2.39.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.40.png" ] && ./build/pbrt focus_2.40.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.41.png" ] && ./build/pbrt focus_2.41.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.42.png" ] && ./build/pbrt focus_2.42.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.43.png" ] && ./build/pbrt focus_2.43.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.44.png" ] && ./build/pbrt focus_2.44.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.45.png" ] && ./build/pbrt focus_2.45.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.46.png" ] && ./build/pbrt focus_2.46.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.47.png" ] && ./build/pbrt focus_2.47.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.48.png" ] && ./build/pbrt focus_2.48.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.49.png" ] && ./build/pbrt focus_2.49.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.50.png" ] && ./build/pbrt focus_2.50.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.51.png" ] && ./build/pbrt focus_2.51.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.52.png" ] && ./build/pbrt focus_2.52.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.53.png" ] && ./build/pbrt focus_2.53.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.54.png" ] && ./build/pbrt focus_2.54.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.55.png" ] && ./build/pbrt focus_2.55.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.56.png" ] && ./build/pbrt focus_2.56.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.57.png" ] && ./build/pbrt focus_2.57.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.58.png" ] && ./build/pbrt focus_2.58.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.59.png" ] && ./build/pbrt focus_2.59.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.60.png" ] && ./build/pbrt focus_2.60.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.61.png" ] && ./build/pbrt focus_2.61.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.62.png" ] && ./build/pbrt focus_2.62.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.63.png" ] && ./build/pbrt focus_2.63.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.64.png" ] && ./build/pbrt focus_2.64.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.65.png" ] && ./build/pbrt focus_2.65.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.66.png" ] && ./build/pbrt focus_2.66.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.67.png" ] && ./build/pbrt focus_2.67.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.68.png" ] && ./build/pbrt focus_2.68.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.69.png" ] && ./build/pbrt focus_2.69.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.70.png" ] && ./build/pbrt focus_2.70.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.71.png" ] && ./build/pbrt focus_2.71.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.72.png" ] && ./build/pbrt focus_2.72.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.73.png" ] && ./build/pbrt focus_2.73.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.74.png" ] && ./build/pbrt focus_2.74.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.75.png" ] && ./build/pbrt focus_2.75.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.76.png" ] && ./build/pbrt focus_2.76.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.77.png" ] && ./build/pbrt focus_2.77.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.78.png" ] && ./build/pbrt focus_2.78.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.79.png" ] && ./build/pbrt focus_2.79.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.80.png" ] && ./build/pbrt focus_2.80.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.81.png" ] && ./build/pbrt focus_2.81.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.82.png" ] && ./build/pbrt focus_2.82.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.83.png" ] && ./build/pbrt focus_2.83.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.84.png" ] && ./build/pbrt focus_2.84.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.85.png" ] && ./build/pbrt focus_2.85.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.86.png" ] && ./build/pbrt focus_2.86.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.87.png" ] && ./build/pbrt focus_2.87.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.88.png" ] && ./build/pbrt focus_2.88.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.89.png" ] && ./build/pbrt focus_2.89.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.90.png" ] && ./build/pbrt focus_2.90.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.91.png" ] && ./build/pbrt focus_2.91.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.92.png" ] && ./build/pbrt focus_2.92.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.93.png" ] && ./build/pbrt focus_2.93.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.94.png" ] && ./build/pbrt focus_2.94.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.95.png" ] && ./build/pbrt focus_2.95.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.96.png" ] && ./build/pbrt focus_2.96.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.97.png" ] && ./build/pbrt focus_2.97.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.98.png" ] && ./build/pbrt focus_2.98.pbrt --nthreads $THREAD_COUNT
[ ! -f "focus2.99.png" ] && ./build/pbrt focus_2.99.pbrt --nthreads $THREAD_COUNT
